---

- name: setup web server
  hosts: all

  tasks:
   - name: Add user ridwan
     ansible.builtin.user:
        name: ridwan
        comment: userridwan
        group: sudo
        groups: ssh
        createhome: yes       
        home: /home/ridwan    
        state: present

   - name: Update apt
     apt: update_cache=yes
     become: yes

   - name: Install Apache
     apt: name=apache2 state=latest
     become: yes

   - name: Install Git
     apt: name=git state=present
     become: yes

   - name: Install curl
     apt: name=curl state=present
     become: yes

   - name: install php and its dependencies
     shell: |
         apt install software-properties-common
         apt update
         apt-get install php8.1-fpm libapache2-mod-php php8.1-dev php8.1-zip php8.1-curl php8.1-mbstring php8.1-pgsql php8.1-gd php8.1-xml -y
     become: yes

   - name: Copy script to remote server
     copy:
       src: postgres.sh
       dest: /home/postgres.sh
     become: yes

   - name: Install postgres and create database
     command: bash /home/postgres.sh
     become: yes

   - name: download composer installer
     shell: |
       curl -sS https://getcomposer.org/installer | php
       mv composer.phar /usr/local/bin/composer
     become: yes

   - name: Take ownership of root folder and clone laravel source code
     shell: |
        cd to /var/www/html
        chown -R $USER /var/www/html
        git clone https://github.com/Ridwan05/Laravel.git temp
        mv temp/* /var/www/html/Laravel
        rm -rf temp
     become: yes

   - name: Change default Apache virtual host
     template:
      src: laravel.tpl
      dest: /etc/apache2/sites-available/Laravel.conf
     become: yes

   - name: Add .env file
     template:
      src: env.tpl
      dest: /var/www/html/Laravel/.env
     become: yes

   - name: Give Laravel Permissions
     shell: |
         chown -R :www-data /var/www/html/Laravel
         chmod -R 775 /var/www/html/Laravel
         chmod -R 775 /var/www/html/Laravel/storage
         chmod -R 775 /var/www/html/Laravel/bootstrap/cache
     become: yes

   - name: Install Laravel Dependencies
     shell: |
        cd /var/www/html/Laravel
        export COMPOSER_ALLOW_SUPERUSER=1; composer show;
        composer update --no-plugins --no-scripts

   - name: Connect Laravel to Database
     shell: |
       cd /var/www/html/Laravel
       php artisan key:generate
       php artisan config:cache
       php artisan migrate

   - name: Enable new config
     shell: |
        cd /var/www/html/Laravel
        a2dissite 000-default.conf
        a2ensite Laravel.conf
        a2enmod rewrite

   - name: restart apache
     service: name=apache2 state=restarted
     become: yes

   - name: Secure Apache with SSL Free Certificate
     shell: |
        cd /var/www/html/Laravel
        apt install python3-certbot-apache -y
        certbot --apache --agree-tos --redirect --hsts --staple-ocsp --email ridohlah74@gmail.com -d www.ridwandemo.me
     become: yes
